name: 'Common Android build setup'
description: "Prepares the build"
outputs: { }
runs:
  using: "composite"
  steps:
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
