name: Android CI

on:
  push:
    branches: [ master, library-swap/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Lint
        run: ./gradlew lintDebug
      - name: Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace
      - name: Android Test Report Action
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ matrix.os == 'ubuntu-latest' }}
